-- 코드를 입력하세요
SELECT p.PRODUCT_ID, p.PRODUCT_NAME, sum(p.PRICE * o.AMOUNT) as TOTAL_SALES
FROM FOOD_PRODUCT p
JOIN FOOD_ORDER o
ON p.PRODUCT_ID = o.PRODUCT_ID
WHERE month(o.PRODUCE_DATE) = 5 and year(o.PRODUCE_DATE) = 2022
group by p.PRODUCT_ID, p.PRODUCT_NAME
order by TOTAL_SALES desc , p.PRODUCT_ID asc